name: Linkcheck

on: [push, pull_request]

jobs:
  linkcheck:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"] # "3.7", , "3.9", "3.10", "3.11"

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install libenchant-2-dev -y
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test external urls
        run: |
          make linkcheck
